language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc
 - g++

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - make distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --enable-minimal
 - make distcheck
